# Seebeck coefficient counts by material family, across DFT-only databases

This notebook pulls entries from **DFT-only** (BoltzTraP/DFT-computed, not experimental) thermoelectric transport databases, classifies each entry into one of three families:

- **half_heusler** — ABC, 1:1:1, space group *F-43m* (216)
- **skutterudite** — M X₃ binary (CoSb₃-type) or filled R M₄X₁₂, space group *Im-3* (204)
- **bi2te3_family** — tetradymite A₂B₃ (Bi/Sb + Te/Se/S), space group *R-3m* (166)

and writes out **one CSV per (dataset, family) combination**, plus a combined summary table.

### Datasets covered
| Section | Dataset | Size | Needs API key? |
|---|---|---|---|
| A | Ricci et al. / Materials Project BoltzTraP (`boltztrap_mp`, via matminer) | 8,924 | No |
| B | JARVIS-DFT (`dft_3d`, via jarvis-tools) | ~76,000 (Seebeck subset ~22,190) | No |
| C (optional) | Full Ricci tabular (`ricci_boltztrap_mp_tabular`, 47,737 entries) + live Materials Project symmetry lookup | 47,737 | **Yes** — free key from https://materialsproject.org/api |

> ⚠️ **Important:** the family classification here is a **heuristic** based on space group + stoichiometry + element sets. It's a strong first pass, but always spot-check a sample of each output CSV (formula + space group columns are included) before treating counts as final. Some real half-Heuslers/skutterudites relax to slightly distorted structures with a different detected space group, so heuristic counts are a lower bound.

Run cells top to bottom. Everything is written to `/content/te_family_csvs/`.

In [1]:
# --- Install dependencies (Colab) ---
!pip install -q matminer pymatgen jarvis-tools mp-api pandas tqdm

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
# --- Imports & shared config ---
import os
import re
import numpy as np
import pandas as pd
from tqdm.auto import tqdm

from pymatgen.core.composition import Composition
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

OUT_DIR = "/content/te_family_csvs"
os.makedirs(OUT_DIR, exist_ok=True)

FAMILIES = ["half_heusler", "skutterudite", "bi2te3_family"]

PNICTOGENS = {"Bi", "Sb", "As"}
CHALCOGENS = {"Te", "Se", "S"}


def classify_family(structure, symprec=0.1):
    """Heuristic classifier: returns one of FAMILIES or None.
    `structure` must be a pymatgen Structure.
    """
    try:
        comp = structure.composition
        reduced = comp.reduced_composition.get_el_amt_dict()
        n_el = len(reduced)
        vals = sorted(reduced.values())
        elements = set(reduced.keys())

        try:
            sga = SpacegroupAnalyzer(structure, symprec=symprec)
            sgnum = sga.get_space_group_number()
        except Exception:
            sgnum = None

        # ---- half-Heusler: ABC, 1:1:1, F-43m (216) ----
        if n_el == 3 and sgnum == 216:
            if abs(vals[0] - vals[1]) < 1e-2 and abs(vals[1] - vals[2]) < 1e-2:
                return "half_heusler"

        # ---- skutterudite: MX3 (binary, Im-3=204) or filled RM4X12 (ternary) ----
        if sgnum == 204:
            if n_el == 2 and vals[0] > 0 and abs(vals[1] / vals[0] - 3) < 0.2:
                return "skutterudite"
            if n_el == 3 and vals[0] > 0:
                if abs(vals[1] / vals[0] - 4) < 0.5 and abs(vals[2] / vals[0] - 12) < 1.0:
                    return "skutterudite"

        # ---- Bi2Te3 family: A2B3 tetradymite, R-3m (166) ----
        if sgnum == 166 and n_el == 2 and vals[0] > 0:
            if abs(vals[1] / vals[0] - 1.5) < 0.15:
                if (elements & PNICTOGENS) and (elements & CHALCOGENS):
                    return "bi2te3_family"

        return None
    except Exception:
        return None


summary_rows = []  # will collect (dataset, family, n_seebeck_datapoints) tuples


def save_family_csv(df, dataset_name, family_name):
    fname = os.path.join(OUT_DIR, f"{dataset_name}__{family_name}.csv")
    df.to_csv(fname, index=False)
    summary_rows.append((dataset_name, family_name, len(df)))
    print(f"  {dataset_name:22s} | {family_name:15s} | {len(df):6d} rows -> {fname}")
    return fname

## Section A — Ricci / Materials Project BoltzTraP (`boltztrap_mp`, matminer)

8,924 entries, self-contained (includes a pymatgen `Structure` object per row) — **no API key needed**.
Columns: `formula, m_n, m_p, mpid, pf_n, pf_p, s_n, s_p, structure`.

In [3]:
from matminer.datasets import load_dataset

df_mp = load_dataset("boltztrap_mp")
print(df_mp.shape)
df_mp.head()

Fetching boltztrap_mp.json.gz from https://ndownloader.figshare.com/files/13297511 to C:\Users\Ekta Jain\Downloads\nbenv311\Lib\site-packages\matminer\datasets\boltztrap_mp.json.gz

Fetching https://ndownloader.figshare.com/files/13297511 in MB:   0%|          | 0.0/14.020266999999999 [00:00<?, ?MB/s]

Fetching https://ndownloader.figshare.com/files/13297511 in MB: 14.020608MB [00:00, 202.42MB/s]

(8924, 9)

,mpid,pf_n,pf_p,s_n,s_p,formula,m_n,m_p,structure
0,mp-10070,0.865,0.0125,-421.0,760.0,BaAg(PO3)3,0.578,72.800,"[[ 0.08245398 10.58009491 11.61923254] O, [3.1..."
1,mp-10086,1.050,0.6440,-393.0,567.0,YSF,0.541,4.020,"[[2.84699546 0.94899849 0. ] F, [0.9489..."
2,mp-10096,0.977,0.4200,-305.0,471.0,Na3Sr3GaP4,0.270,1.020,"[[-2.8085287 7.06608376 1.25800196] Na, [1...."
3,mp-10103,0.889,0.0257,-416.0,871.0,YbLiAlF6,0.548,20.300,"[[2.52287112 1.45658029 7.18290524] Li, [-2.85..."
4,mp-10155,0.719,1.5700,-496.0,510.0,P2Ir,1.160,0.667,"[[0.86371064 5.14343422 4.80450637] P, [4.5512..."

In [4]:
# Classify each entry and keep only rows with a usable Seebeck value (s_n and/or s_p)
tqdm.pandas(desc="classifying boltztrap_mp")
df_mp["family"] = df_mp["structure"].progress_apply(classify_family)
df_mp["space_group_number"] = df_mp["structure"].apply(
    lambda s: SpacegroupAnalyzer(s, symprec=0.1).get_space_group_number() if s is not None else None
)

df_mp_export = df_mp[["mpid", "formula", "space_group_number", "family", "s_n", "s_p", "m_n", "m_p", "pf_n", "pf_p"]].copy()

print("Family counts (all entries, before filtering for non-null Seebeck):")
print(df_mp_export["family"].value_counts(dropna=True))

print("\nSaving per-family CSVs (rows with at least one non-null Seebeck value: s_n or s_p) ...")
for fam in FAMILIES:
    sub = df_mp_export[
        (df_mp_export["family"] == fam)
        & (df_mp_export[["s_n", "s_p"]].notna().any(axis=1))
    ]
    save_family_csv(sub, "ricci_boltztrap_mp", fam)

classifying boltztrap_mp:   0%|          | 0/8924 [00:00<?, ?it/s]

C:\Users\Ekta Jain\AppData\Local\Programs\Python\Python311\Lib\functools.py:1001: UserWarning: No Pauling electronegativity for Ar. Setting to NaN. This has no physical meaning, and is mainly done to avoid errors caused by the code expecting a float.
  val = self.func(instance)

Family counts (all entries, before filtering for non-null Seebeck):
family
half_heusler    9
skutterudite    1
Name: count, dtype: int64

Saving per-family CSVs (rows with at least one non-null Seebeck value: s_n or s_p) ...
  ricci_boltztrap_mp     | half_heusler    |      9 rows -> /content/te_family_csvs\ricci_boltztrap_mp__half_heusler.csv
  ricci_boltztrap_mp     | skutterudite    |      1 rows -> /content/te_family_csvs\ricci_boltztrap_mp__skutterudite.csv
  ricci_boltztrap_mp     | bi2te3_family   |      0 rows -> /content/te_family_csvs\ricci_boltztrap_mp__bi2te3_family.csv

## Section B — JARVIS-DFT (`dft_3d`, jarvis-tools)

~76,000 total DFT entries; Seebeck coefficients (`n-Seebeck`, `p-Seebeck`) computed via BoltzTraP for a subset (~22,190). No API key needed — downloads from NIST figshare on first call (can take a few minutes).

In [5]:
from jarvis.db.figshare import data as jarvis_data
from jarvis.core.atoms import Atoms as JarvisAtoms

dft_3d = jarvis_data(dataset="dft_3d")  # first run downloads ~1-2 GB, be patient
print("Total JARVIS-DFT 3D entries:", len(dft_3d))
print("Example keys:", sorted(dft_3d[0].keys())[:20], "...")

Obtaining 3D dataset 94k ...
Reference:https://doi.org/10.1016/j.commatsci.2025.114063
Other versions:https://doi.org/10.6084/m9.figshare.6815699

  0%|          | 0.00/48.4M [00:00<?, ?iB/s]

  0%|          | 17.4k/48.4M [00:00<07:53, 102kiB/s]

  0%|          | 69.6k/48.4M [00:00<03:43, 217kiB/s]

  0%|          | 174k/48.4M [00:00<02:02, 393kiB/s]

  0%|          | 214k/48.4M [00:00<02:28, 324kiB/s]

  1%|          | 313k/48.4M [00:00<01:56, 413kiB/s]

  1%|          | 355k/48.4M [00:01<02:17, 350kiB/s]

  1%|          | 487k/48.4M [00:01<01:37, 490kiB/s]

  1%|▏         | 609k/48.4M [00:01<01:54, 420kiB/s]

  2%|▏         | 766k/48.4M [00:01<01:28, 536kiB/s]

  2%|▏         | 824k/48.4M [00:01<01:32, 513kiB/s]

  2%|▏         | 939k/48.4M [00:02<01:26, 547kiB/s]

  2%|▏         | 1.04M/48.4M [00:02<01:24, 562kiB/s]

  2%|▏         | 1.17M/48.4M [00:02<01:18, 600kiB/s]

  3%|▎         | 1.31M/48.4M [00:02<01:10, 671kiB/s]

  3%|▎         | 1.43M/48.4M [00:02<01:09, 675kiB/s]

  3%|▎         | 1.50M/48.4M [00:02<01:23, 563kiB/s]

  3%|▎         | 1.57M/48.4M [00:03<01:26, 539kiB/s]

  3%|▎         | 1.62M/48.4M [00:03<01:45, 444kiB/s]

  3%|▎         | 1.67M/48.4M [00:03<01:50, 422kiB/s]

  4%|▎         | 1.74M/48.4M [00:03<01:54, 409kiB/s]

  4%|▎         | 1.81M/48.4M [00:03<01:55, 405kiB/s]

  4%|▍         | 1.88M/48.4M [00:03<01:53, 409kiB/s]

  4%|▍         | 1.95M/48.4M [00:04<01:54, 407kiB/s]

  4%|▍         | 2.02M/48.4M [00:04<01:56, 398kiB/s]

  4%|▍         | 2.09M/48.4M [00:04<01:55, 402kiB/s]

  4%|▍         | 2.18M/48.4M [00:04<01:47, 431kiB/s]

  5%|▍         | 2.23M/48.4M [00:05<02:35, 298kiB/s]

  5%|▍         | 2.35M/48.4M [00:05<01:54, 403kiB/s]

  5%|▍         | 2.42M/48.4M [00:05<02:01, 380kiB/s]

  5%|▌         | 2.47M/48.4M [00:05<02:02, 374kiB/s]

  5%|▌         | 2.52M/48.4M [00:05<02:09, 354kiB/s]

  5%|▌         | 2.59M/48.4M [00:05<02:10, 350kiB/s]

  5%|▌         | 2.65M/48.4M [00:06<02:11, 349kiB/s]

  6%|▌         | 2.71M/48.4M [00:06<01:54, 400kiB/s]

  6%|▌         | 2.76M/48.4M [00:06<02:01, 376kiB/s]

  6%|▌         | 2.80M/48.4M [00:06<02:04, 367kiB/s]

  6%|▌         | 2.84M/48.4M [00:06<02:12, 343kiB/s]

  6%|▌         | 2.89M/48.4M [00:06<02:06, 361kiB/s]

  6%|▌         | 2.94M/48.4M [00:06<02:05, 362kiB/s]

  6%|▌         | 2.98M/48.4M [00:07<02:11, 346kiB/s]

  6%|▋         | 3.03M/48.4M [00:07<02:10, 347kiB/s]

  6%|▋         | 3.10M/48.4M [00:07<01:53, 400kiB/s]

  6%|▋         | 3.14M/48.4M [00:07<01:59, 378kiB/s]

  7%|▋         | 3.18M/48.4M [00:07<02:08, 353kiB/s]

  7%|▋         | 3.22M/48.4M [00:07<02:13, 338kiB/s]

  7%|▋         | 3.29M/48.4M [00:07<02:05, 360kiB/s]

  7%|▋         | 3.34M/48.4M [00:07<02:01, 372kiB/s]

  7%|▋         | 3.39M/48.4M [00:08<01:55, 390kiB/s]

  7%|▋         | 3.43M/48.4M [00:08<02:02, 367kiB/s]

  7%|▋         | 3.48M/48.4M [00:08<02:07, 353kiB/s]

  7%|▋         | 3.55M/48.4M [00:08<02:01, 369kiB/s]

  7%|▋         | 3.60M/48.4M [00:08<01:59, 374kiB/s]

  8%|▊         | 3.66M/48.4M [00:08<01:55, 389kiB/s]

  8%|▊         | 3.71M/48.4M [00:08<01:53, 395kiB/s]

  8%|▊         | 3.75M/48.4M [00:09<01:53, 393kiB/s]

  8%|▊         | 3.79M/48.4M [00:09<01:51, 399kiB/s]

  8%|▊         | 3.85M/48.4M [00:09<01:53, 393kiB/s]

  8%|▊         | 3.89M/48.4M [00:09<01:53, 394kiB/s]

  8%|▊         | 3.93M/48.4M [00:09<01:50, 403kiB/s]

  8%|▊         | 3.99M/48.4M [00:09<01:50, 404kiB/s]

  8%|▊         | 4.03M/48.4M [00:09<01:53, 392kiB/s]

  8%|▊         | 4.09M/48.4M [00:09<01:40, 442kiB/s]

  9%|▊         | 4.14M/48.4M [00:09<01:49, 405kiB/s]

  9%|▊         | 4.18M/48.4M [00:10<01:56, 381kiB/s]

  9%|▉         | 4.25M/48.4M [00:10<01:47, 410kiB/s]

  9%|▉         | 4.30M/48.4M [00:10<01:42, 430kiB/s]

  9%|▉         | 4.34M/48.4M [00:10<01:41, 433kiB/s]

  9%|▉         | 4.40M/48.4M [00:10<01:51, 397kiB/s]

  9%|▉         | 4.47M/48.4M [00:10<01:42, 429kiB/s]

  9%|▉         | 4.53M/48.4M [00:10<01:40, 438kiB/s]

  9%|▉         | 4.59M/48.4M [00:11<01:31, 479kiB/s]

 10%|▉         | 4.64M/48.4M [00:11<01:35, 459kiB/s]

 10%|▉         | 4.70M/48.4M [00:11<01:31, 479kiB/s]

 10%|▉         | 4.75M/48.4M [00:11<01:33, 466kiB/s]

 10%|▉         | 4.80M/48.4M [00:11<01:36, 454kiB/s]

 10%|█         | 4.87M/48.4M [00:11<01:27, 496kiB/s]

 10%|█         | 4.93M/48.4M [00:11<01:28, 493kiB/s]

 10%|█         | 5.00M/48.4M [00:11<01:25, 509kiB/s]

 10%|█         | 5.08M/48.4M [00:11<01:15, 578kiB/s]

 11%|█         | 5.15M/48.4M [00:12<01:17, 561kiB/s]

 11%|█         | 5.24M/48.4M [00:12<01:14, 578kiB/s]

 11%|█         | 5.33M/48.4M [00:12<01:10, 610kiB/s]

 11%|█         | 5.41M/48.4M [00:12<01:05, 659kiB/s]

 11%|█▏        | 5.48M/48.4M [00:12<01:07, 637kiB/s]

 11%|█▏        | 5.57M/48.4M [00:12<01:04, 660kiB/s]

 12%|█▏        | 5.66M/48.4M [00:13<01:29, 476kiB/s]

 12%|█▏        | 5.80M/48.4M [00:13<01:14, 570kiB/s]

 12%|█▏        | 5.94M/48.4M [00:13<01:01, 687kiB/s]

 12%|█▏        | 6.01M/48.4M [00:13<01:23, 507kiB/s]

 13%|█▎        | 6.11M/48.4M [00:13<01:19, 535kiB/s]

 13%|█▎        | 6.18M/48.4M [00:13<01:25, 495kiB/s]

 13%|█▎        | 6.25M/48.4M [00:14<01:23, 508kiB/s]

 13%|█▎        | 6.30M/48.4M [00:14<01:43, 406kiB/s]

 13%|█▎        | 6.39M/48.4M [00:14<01:28, 474kiB/s]

 13%|█▎        | 6.44M/48.4M [00:14<01:39, 423kiB/s]

 13%|█▎        | 6.49M/48.4M [00:14<01:51, 378kiB/s]

 14%|█▎        | 6.55M/48.4M [00:14<01:48, 385kiB/s]

 14%|█▎        | 6.59M/48.4M [00:15<01:48, 384kiB/s]

 14%|█▎        | 6.63M/48.4M [00:15<01:51, 376kiB/s]

 14%|█▍        | 6.67M/48.4M [00:15<01:54, 366kiB/s]

 14%|█▍        | 6.71M/48.4M [00:15<01:58, 354kiB/s]

 14%|█▍        | 6.74M/48.4M [00:15<01:59, 349kiB/s]

 14%|█▍        | 6.79M/48.4M [00:15<01:56, 358kiB/s]

 14%|█▍        | 6.84M/48.4M [00:15<01:47, 389kiB/s]

 14%|█▍        | 6.88M/48.4M [00:15<02:03, 337kiB/s]

 14%|█▍        | 6.93M/48.4M [00:15<02:01, 343kiB/s]

 14%|█▍        | 7.00M/48.4M [00:16<01:43, 399kiB/s]

 15%|█▍        | 7.04M/48.4M [00:16<01:46, 389kiB/s]

 15%|█▍        | 7.08M/48.4M [00:16<02:01, 340kiB/s]

 15%|█▍        | 7.12M/48.4M [00:16<02:02, 336kiB/s]

 15%|█▍        | 7.19M/48.4M [00:16<01:51, 370kiB/s]

 15%|█▍        | 7.24M/48.4M [00:16<01:48, 380kiB/s]

 15%|█▌        | 7.28M/48.4M [00:16<01:52, 366kiB/s]

 15%|█▌        | 7.32M/48.4M [00:17<01:53, 362kiB/s]

 15%|█▌        | 7.36M/48.4M [00:17<01:47, 383kiB/s]

 15%|█▌        | 7.40M/48.4M [00:17<01:54, 358kiB/s]

 15%|█▌        | 7.45M/48.4M [00:17<01:52, 363kiB/s]

 15%|█▌        | 7.50M/48.4M [00:17<01:49, 374kiB/s]

 16%|█▌        | 7.54M/48.4M [00:17<01:51, 366kiB/s]

 16%|█▌        | 7.58M/48.4M [00:17<01:54, 356kiB/s]

 16%|█▌        | 7.64M/48.4M [00:17<01:53, 359kiB/s]

 16%|█▌        | 7.71M/48.4M [00:18<01:49, 374kiB/s]

 16%|█▌        | 7.76M/48.4M [00:18<01:40, 407kiB/s]

 16%|█▌        | 7.81M/48.4M [00:18<01:43, 393kiB/s]

 16%|█▌        | 7.85M/48.4M [00:18<01:47, 376kiB/s]

 16%|█▋        | 7.92M/48.4M [00:18<01:34, 427kiB/s]

 16%|█▋        | 7.96M/48.4M [00:18<01:36, 421kiB/s]

 17%|█▋        | 8.01M/48.4M [00:18<01:37, 414kiB/s]

 17%|█▋        | 8.05M/48.4M [00:18<01:39, 405kiB/s]

 17%|█▋        | 8.09M/48.4M [00:19<01:44, 387kiB/s]

 17%|█▋        | 8.13M/48.4M [00:19<01:51, 363kiB/s]

 17%|█▋        | 8.18M/48.4M [00:19<01:40, 402kiB/s]

 17%|█▋        | 8.22M/48.4M [00:19<01:42, 392kiB/s]

 17%|█▋        | 8.29M/48.4M [00:19<01:34, 425kiB/s]

 17%|█▋        | 8.34M/48.4M [00:19<01:35, 419kiB/s]

 17%|█▋        | 8.39M/48.4M [00:19<01:32, 432kiB/s]

 17%|█▋        | 8.43M/48.4M [00:19<01:35, 420kiB/s]

 18%|█▊        | 8.50M/48.4M [00:19<01:31, 436kiB/s]

 18%|█▊        | 8.56M/48.4M [00:20<01:28, 450kiB/s]

 18%|█▊        | 8.61M/48.4M [00:20<01:32, 431kiB/s]

 18%|█▊        | 8.67M/48.4M [00:20<01:29, 444kiB/s]

 18%|█▊        | 8.72M/48.4M [00:20<01:28, 449kiB/s]

 18%|█▊        | 8.77M/48.4M [00:20<01:27, 455kiB/s]

 18%|█▊        | 8.84M/48.4M [00:20<01:22, 482kiB/s]

 18%|█▊        | 8.91M/48.4M [00:20<01:15, 521kiB/s]

 19%|█▊        | 8.97M/48.4M [00:20<01:17, 508kiB/s]

 19%|█▊        | 9.03M/48.4M [00:21<01:16, 515kiB/s]

 19%|█▉        | 9.10M/48.4M [00:21<01:11, 548kiB/s]

 19%|█▉        | 9.16M/48.4M [00:21<01:12, 542kiB/s]

 19%|█▉        | 9.24M/48.4M [00:21<01:10, 558kiB/s]

 19%|█▉        | 9.31M/48.4M [00:21<01:06, 592kiB/s]

 19%|█▉        | 9.37M/48.4M [00:21<01:07, 575kiB/s]

 20%|█▉        | 9.47M/48.4M [00:21<01:01, 631kiB/s]

 20%|█▉        | 9.56M/48.4M [00:21<00:56, 687kiB/s]

 20%|█▉        | 9.63M/48.4M [00:21<00:58, 669kiB/s]

 20%|██        | 9.73M/48.4M [00:22<00:56, 688kiB/s]

 20%|██        | 9.85M/48.4M [00:22<00:49, 783kiB/s]

 21%|██        | 9.93M/48.4M [00:22<01:11, 540kiB/s]

 21%|██        | 10.1M/48.4M [00:22<01:04, 596kiB/s]

 21%|██        | 10.1M/48.4M [00:22<01:05, 586kiB/s]

 21%|██        | 10.3M/48.4M [00:23<01:01, 619kiB/s]

 21%|██▏       | 10.3M/48.4M [00:23<01:16, 497kiB/s]

 22%|██▏       | 10.4M/48.4M [00:23<01:06, 575kiB/s]

 22%|██▏       | 10.5M/48.4M [00:23<01:04, 585kiB/s]

 22%|██▏       | 10.6M/48.4M [00:23<01:04, 583kiB/s]

 22%|██▏       | 10.6M/48.4M [00:23<01:14, 509kiB/s]

 22%|██▏       | 10.7M/48.4M [00:23<01:14, 507kiB/s]

 22%|██▏       | 10.8M/48.4M [00:24<01:10, 536kiB/s]

 22%|██▏       | 10.8M/48.4M [00:24<01:09, 541kiB/s]

 22%|██▏       | 10.9M/48.4M [00:24<01:15, 497kiB/s]

 23%|██▎       | 10.9M/48.4M [00:24<01:07, 553kiB/s]

 23%|██▎       | 11.0M/48.4M [00:24<01:08, 548kiB/s]

 23%|██▎       | 11.1M/48.4M [00:24<01:12, 513kiB/s]

 23%|██▎       | 11.1M/48.4M [00:24<01:07, 552kiB/s]

 23%|██▎       | 11.2M/48.4M [00:24<01:07, 552kiB/s]

 23%|██▎       | 11.3M/48.4M [00:24<01:12, 510kiB/s]

 23%|██▎       | 11.3M/48.4M [00:25<01:05, 567kiB/s]

 24%|██▎       | 11.4M/48.4M [00:25<01:04, 572kiB/s]

 24%|██▎       | 11.4M/48.4M [00:25<01:12, 512kiB/s]

 24%|██▍       | 11.5M/48.4M [00:25<01:06, 556kiB/s]

 24%|██▍       | 11.6M/48.4M [00:25<01:04, 573kiB/s]

 24%|██▍       | 11.7M/48.4M [00:25<01:05, 559kiB/s]

 24%|██▍       | 11.7M/48.4M [00:25<01:10, 518kiB/s]

 24%|██▍       | 11.8M/48.4M [00:25<01:04, 567kiB/s]

 25%|██▍       | 11.9M/48.4M [00:26<01:01, 596kiB/s]

 25%|██▍       | 12.0M/48.4M [00:26<01:04, 567kiB/s]

 25%|██▍       | 12.0M/48.4M [00:26<01:11, 509kiB/s]

 25%|██▌       | 12.1M/48.4M [00:26<01:03, 576kiB/s]

 25%|██▌       | 12.2M/48.4M [00:26<01:02, 583kiB/s]

 25%|██▌       | 12.3M/48.4M [00:26<01:03, 572kiB/s]

 25%|██▌       | 12.3M/48.4M [00:26<01:11, 508kiB/s]

 26%|██▌       | 12.4M/48.4M [00:26<01:02, 576kiB/s]

 26%|██▌       | 12.5M/48.4M [00:27<01:01, 588kiB/s]

 26%|██▌       | 12.6M/48.4M [00:27<01:03, 567kiB/s]

 26%|██▌       | 12.6M/48.4M [00:27<01:08, 521kiB/s]

 26%|██▌       | 12.7M/48.4M [00:27<01:00, 586kiB/s]

 26%|██▋       | 12.8M/48.4M [00:27<01:01, 580kiB/s]

 27%|██▋       | 12.9M/48.4M [00:27<01:01, 574kiB/s]

 27%|██▋       | 12.9M/48.4M [00:27<01:08, 517kiB/s]

 27%|██▋       | 13.0M/48.4M [00:28<01:00, 585kiB/s]

 27%|██▋       | 13.1M/48.4M [00:28<00:59, 590kiB/s]

 27%|██▋       | 13.2M/48.4M [00:28<01:03, 559kiB/s]

 27%|██▋       | 13.2M/48.4M [00:28<01:03, 559kiB/s]

 27%|██▋       | 13.3M/48.4M [00:28<00:57, 606kiB/s]

 28%|██▊       | 13.4M/48.4M [00:28<00:57, 608kiB/s]

 28%|██▊       | 13.4M/48.4M [00:28<01:03, 549kiB/s]

 28%|██▊       | 13.5M/48.4M [00:28<00:56, 622kiB/s]

 28%|██▊       | 13.6M/48.4M [00:29<00:58, 600kiB/s]

 28%|██▊       | 13.7M/48.4M [00:29<00:57, 603kiB/s]

 28%|██▊       | 13.8M/48.4M [00:29<00:58, 593kiB/s]

 29%|██▊       | 13.9M/48.4M [00:29<00:58, 593kiB/s]

 29%|██▉       | 14.0M/48.4M [00:29<00:49, 694kiB/s]

 29%|██▉       | 14.1M/48.4M [00:29<00:53, 646kiB/s]

 29%|██▉       | 14.1M/48.4M [00:29<00:53, 638kiB/s]

 29%|██▉       | 14.2M/48.4M [00:30<00:52, 646kiB/s]

 30%|██▉       | 14.4M/48.4M [00:30<00:50, 671kiB/s]

 30%|██▉       | 14.5M/48.4M [00:30<00:46, 733kiB/s]

 30%|███       | 14.6M/48.4M [00:30<01:03, 532kiB/s]

 30%|███       | 14.8M/48.4M [00:30<00:44, 766kiB/s]

 31%|███       | 14.9M/48.4M [00:30<00:48, 696kiB/s]

 31%|███       | 14.9M/48.4M [00:31<01:00, 550kiB/s]

 31%|███       | 15.0M/48.4M [00:31<00:53, 623kiB/s]

 31%|███       | 15.1M/48.4M [00:31<00:58, 569kiB/s]

 31%|███▏      | 15.2M/48.4M [00:31<01:22, 404kiB/s]

 32%|███▏      | 15.3M/48.4M [00:31<01:06, 500kiB/s]

 32%|███▏      | 15.3M/48.4M [00:32<01:11, 461kiB/s]

 32%|███▏      | 15.4M/48.4M [00:32<01:16, 431kiB/s]

 32%|███▏      | 15.5M/48.4M [00:32<01:26, 382kiB/s]

 32%|███▏      | 15.5M/48.4M [00:32<01:26, 380kiB/s]

 32%|███▏      | 15.6M/48.4M [00:32<01:25, 384kiB/s]

 32%|███▏      | 15.6M/48.4M [00:32<01:33, 351kiB/s]

 32%|███▏      | 15.7M/48.4M [00:33<01:29, 365kiB/s]

 33%|███▎      | 15.8M/48.4M [00:33<01:27, 376kiB/s]

 33%|███▎      | 15.8M/48.4M [00:33<01:26, 376kiB/s]

 33%|███▎      | 15.9M/48.4M [00:33<01:20, 405kiB/s]

 33%|███▎      | 15.9M/48.4M [00:33<01:27, 372kiB/s]

 33%|███▎      | 16.0M/48.4M [00:33<01:27, 369kiB/s]

 33%|███▎      | 16.0M/48.4M [00:33<01:22, 393kiB/s]

 33%|███▎      | 16.1M/48.4M [00:34<01:21, 396kiB/s]

 33%|███▎      | 16.1M/48.4M [00:34<01:22, 392kiB/s]

 33%|███▎      | 16.2M/48.4M [00:34<01:29, 362kiB/s]

 33%|███▎      | 16.2M/48.4M [00:34<01:23, 385kiB/s]

 34%|███▎      | 16.3M/48.4M [00:34<01:25, 376kiB/s]

 34%|███▎      | 16.3M/48.4M [00:34<01:27, 368kiB/s]

 34%|███▍      | 16.4M/48.4M [00:34<01:29, 360kiB/s]

 34%|███▍      | 16.4M/48.4M [00:35<01:25, 372kiB/s]

 34%|███▍      | 16.5M/48.4M [00:35<01:22, 390kiB/s]

 34%|███▍      | 16.6M/48.4M [00:35<01:18, 406kiB/s]

 34%|███▍      | 16.6M/48.4M [00:35<01:18, 407kiB/s]

 34%|███▍      | 16.6M/48.4M [00:35<01:24, 377kiB/s]

 34%|███▍      | 16.7M/48.4M [00:35<01:22, 386kiB/s]

 35%|███▍      | 16.8M/48.4M [00:36<01:47, 295kiB/s]

 35%|███▍      | 16.9M/48.4M [00:36<01:19, 398kiB/s]

 35%|███▍      | 16.9M/48.4M [00:36<01:26, 366kiB/s]

 35%|███▍      | 17.0M/48.4M [00:36<01:29, 353kiB/s]

 35%|███▌      | 17.0M/48.4M [00:36<01:24, 373kiB/s]

 35%|███▌      | 17.0M/48.4M [00:36<01:29, 350kiB/s]

 35%|███▌      | 17.1M/48.4M [00:36<01:28, 356kiB/s]

 35%|███▌      | 17.1M/48.4M [00:36<01:24, 369kiB/s]

 35%|███▌      | 17.2M/48.4M [00:37<01:26, 363kiB/s]

 36%|███▌      | 17.2M/48.4M [00:37<01:31, 340kiB/s]

 36%|███▌      | 17.3M/48.4M [00:37<01:30, 343kiB/s]

 36%|███▌      | 17.3M/48.4M [00:37<01:26, 361kiB/s]

 36%|███▌      | 17.4M/48.4M [00:37<01:23, 372kiB/s]

 36%|███▌      | 17.5M/48.4M [00:37<01:19, 391kiB/s]

 36%|███▌      | 17.5M/48.4M [00:37<01:09, 442kiB/s]

 36%|███▋      | 17.6M/48.4M [00:38<01:13, 419kiB/s]

 36%|███▋      | 17.6M/48.4M [00:38<01:16, 402kiB/s]

 37%|███▋      | 17.7M/48.4M [00:38<01:24, 364kiB/s]

 37%|███▋      | 17.8M/48.4M [00:38<01:11, 428kiB/s]

 37%|███▋      | 17.8M/48.4M [00:38<01:13, 418kiB/s]

 37%|███▋      | 17.8M/48.4M [00:38<01:17, 397kiB/s]

 37%|███▋      | 17.9M/48.4M [00:38<01:17, 392kiB/s]

 37%|███▋      | 18.0M/48.4M [00:39<01:17, 393kiB/s]

 37%|███▋      | 18.1M/48.4M [00:39<01:14, 406kiB/s]

 37%|███▋      | 18.1M/48.4M [00:39<01:07, 452kiB/s]

 38%|███▊      | 18.2M/48.4M [00:39<01:07, 445kiB/s]

 38%|███▊      | 18.2M/48.4M [00:39<01:13, 412kiB/s]

 38%|███▊      | 18.3M/48.4M [00:39<01:11, 420kiB/s]

 38%|███▊      | 18.3M/48.4M [00:39<01:12, 418kiB/s]

 38%|███▊      | 18.4M/48.4M [00:39<01:14, 405kiB/s]

 38%|███▊      | 18.4M/48.4M [00:40<01:17, 386kiB/s]

 38%|███▊      | 18.5M/48.4M [00:40<01:17, 386kiB/s]

 38%|███▊      | 18.6M/48.4M [00:40<01:06, 453kiB/s]

 38%|███▊      | 18.6M/48.4M [00:40<01:06, 448kiB/s]

 38%|███▊      | 18.7M/48.4M [00:40<01:10, 424kiB/s]

 39%|███▊      | 18.7M/48.4M [00:40<01:11, 417kiB/s]

 39%|███▊      | 18.7M/48.4M [00:40<01:11, 414kiB/s]

 39%|███▉      | 18.8M/48.4M [00:41<01:15, 392kiB/s]

 39%|███▉      | 18.9M/48.4M [00:41<01:05, 450kiB/s]

 39%|███▉      | 18.9M/48.4M [00:41<01:06, 443kiB/s]

 39%|███▉      | 18.9M/48.4M [00:41<01:12, 407kiB/s]

 39%|███▉      | 19.0M/48.4M [00:41<01:05, 450kiB/s]

 39%|███▉      | 19.1M/48.4M [00:41<01:07, 438kiB/s]

 39%|███▉      | 19.1M/48.4M [00:41<01:11, 413kiB/s]

 40%|███▉      | 19.2M/48.4M [00:41<01:03, 464kiB/s]

 40%|███▉      | 19.2M/48.4M [00:41<01:04, 451kiB/s]

 40%|███▉      | 19.3M/48.4M [00:42<01:06, 439kiB/s]

 40%|███▉      | 19.3M/48.4M [00:42<01:03, 458kiB/s]

 40%|███▉      | 19.4M/48.4M [00:42<01:02, 463kiB/s]

 40%|████      | 19.4M/48.4M [00:42<01:04, 451kiB/s]

 40%|████      | 19.5M/48.4M [00:42<00:57, 500kiB/s]

 40%|████      | 19.5M/48.4M [00:42<00:58, 490kiB/s]

 40%|████      | 19.6M/48.4M [00:42<01:02, 462kiB/s]

 41%|████      | 19.7M/48.4M [00:42<00:51, 554kiB/s]

 41%|████      | 19.7M/48.4M [00:42<00:53, 540kiB/s]

 41%|████      | 19.8M/48.4M [00:43<00:56, 504kiB/s]

 41%|████      | 19.9M/48.4M [00:43<00:50, 561kiB/s]

 41%|████      | 19.9M/48.4M [00:43<00:51, 553kiB/s]

 41%|████▏     | 20.0M/48.4M [00:43<00:53, 532kiB/s]

 41%|████▏     | 20.1M/48.4M [00:43<00:46, 614kiB/s]

 42%|████▏     | 20.2M/48.4M [00:43<00:47, 600kiB/s]

 42%|████▏     | 20.2M/48.4M [00:43<00:48, 586kiB/s]

 42%|████▏     | 20.3M/48.4M [00:43<00:40, 700kiB/s]

 42%|████▏     | 20.4M/48.4M [00:44<00:41, 679kiB/s]

 42%|████▏     | 20.5M/48.4M [00:44<00:43, 636kiB/s]

 42%|████▏     | 20.6M/48.4M [00:44<00:39, 715kiB/s]

 43%|████▎     | 20.6M/48.4M [00:44<00:38, 716kiB/s]

 43%|████▎     | 20.8M/48.4M [00:44<00:38, 713kiB/s]

 43%|████▎     | 20.8M/48.4M [00:44<00:51, 536kiB/s]

 43%|████▎     | 21.0M/48.4M [00:44<00:36, 744kiB/s]

 43%|████▎     | 21.1M/48.4M [00:44<00:36, 751kiB/s]

 44%|████▎     | 21.1M/48.4M [00:45<00:38, 715kiB/s]

 44%|████▍     | 21.2M/48.4M [00:45<00:42, 637kiB/s]

 44%|████▍     | 21.3M/48.4M [00:45<00:39, 679kiB/s]

 44%|████▍     | 21.4M/48.4M [00:45<00:38, 697kiB/s]

 44%|████▍     | 21.5M/48.4M [00:45<00:40, 673kiB/s]

 44%|████▍     | 21.6M/48.4M [00:45<00:39, 679kiB/s]

 45%|████▍     | 21.7M/48.4M [00:46<00:53, 502kiB/s]

 45%|████▌     | 21.8M/48.4M [00:46<00:37, 706kiB/s]

 45%|████▌     | 21.9M/48.4M [00:46<00:42, 625kiB/s]

 45%|████▌     | 22.0M/48.4M [00:46<00:41, 640kiB/s]

 46%|████▌     | 22.1M/48.4M [00:46<00:41, 641kiB/s]

 46%|████▌     | 22.1M/48.4M [00:46<00:42, 616kiB/s]

 46%|████▌     | 22.2M/48.4M [00:46<00:46, 567kiB/s]

 46%|████▌     | 22.3M/48.4M [00:46<00:45, 581kiB/s]

 46%|████▌     | 22.4M/48.4M [00:47<00:44, 588kiB/s]

 46%|████▋     | 22.5M/48.4M [00:47<00:40, 634kiB/s]

 47%|████▋     | 22.5M/48.4M [00:47<00:41, 627kiB/s]

 47%|████▋     | 22.6M/48.4M [00:47<00:42, 614kiB/s]

 47%|████▋     | 22.7M/48.4M [00:47<00:43, 597kiB/s]

 47%|████▋     | 22.7M/48.4M [00:47<00:43, 589kiB/s]

 47%|████▋     | 22.8M/48.4M [00:47<00:42, 603kiB/s]

 47%|████▋     | 22.9M/48.4M [00:48<00:41, 620kiB/s]

 47%|████▋     | 23.0M/48.4M [00:48<00:41, 618kiB/s]

 48%|████▊     | 23.1M/48.4M [00:48<00:40, 620kiB/s]

 48%|████▊     | 23.2M/48.4M [00:48<00:40, 621kiB/s]

 48%|████▊     | 23.2M/48.4M [00:48<00:37, 672kiB/s]

 48%|████▊     | 23.3M/48.4M [00:48<00:38, 656kiB/s]

 48%|████▊     | 23.4M/48.4M [00:48<00:40, 622kiB/s]

 48%|████▊     | 23.5M/48.4M [00:48<00:36, 682kiB/s]

 49%|████▊     | 23.5M/48.4M [00:48<00:37, 665kiB/s]

 49%|████▊     | 23.6M/48.4M [00:49<00:56, 440kiB/s]

 49%|████▉     | 23.7M/48.4M [00:49<00:43, 565kiB/s]

 49%|████▉     | 23.8M/48.4M [00:49<00:42, 581kiB/s]

 49%|████▉     | 23.9M/48.4M [00:49<00:43, 564kiB/s]

 49%|████▉     | 23.9M/48.4M [00:49<00:48, 504kiB/s]

 50%|████▉     | 24.0M/48.4M [00:49<00:48, 506kiB/s]

 50%|████▉     | 24.0M/48.4M [00:50<00:49, 496kiB/s]

 50%|████▉     | 24.1M/48.4M [00:50<00:49, 494kiB/s]

 50%|████▉     | 24.2M/48.4M [00:50<00:49, 490kiB/s]

 50%|█████     | 24.3M/48.4M [00:50<00:43, 552kiB/s]

 50%|█████     | 24.3M/48.4M [00:50<00:42, 572kiB/s]

 50%|█████     | 24.4M/48.4M [00:50<00:45, 534kiB/s]

 51%|█████     | 24.5M/48.4M [00:50<00:40, 588kiB/s]

 51%|█████     | 24.5M/48.4M [00:50<00:55, 434kiB/s]

 51%|█████     | 24.7M/48.4M [00:51<00:44, 535kiB/s]

 51%|█████     | 24.7M/48.4M [00:51<00:48, 491kiB/s]

 51%|█████     | 24.8M/48.4M [00:51<00:47, 498kiB/s]

 51%|█████▏    | 24.9M/48.4M [00:51<00:50, 465kiB/s]

 52%|█████▏    | 25.0M/48.4M [00:51<00:49, 475kiB/s]

 52%|█████▏    | 25.1M/48.4M [00:52<00:48, 480kiB/s]

 52%|█████▏    | 25.1M/48.4M [00:52<00:51, 453kiB/s]

 52%|█████▏    | 25.2M/48.4M [00:52<00:49, 471kiB/s]

 52%|█████▏    | 25.3M/48.4M [00:52<01:02, 372kiB/s]

 52%|█████▏    | 25.4M/48.4M [00:52<00:51, 451kiB/s]

 52%|█████▏    | 25.4M/48.4M [00:52<00:56, 405kiB/s]

 53%|█████▎    | 25.5M/48.4M [00:53<00:57, 403kiB/s]

 53%|█████▎    | 25.6M/48.4M [00:53<01:01, 374kiB/s]

 53%|█████▎    | 25.6M/48.4M [00:53<01:00, 380kiB/s]

 53%|█████▎    | 25.7M/48.4M [00:53<00:57, 396kiB/s]

 53%|█████▎    | 25.7M/48.4M [00:53<00:57, 396kiB/s]

 53%|█████▎    | 25.8M/48.4M [00:53<00:53, 425kiB/s]

 53%|█████▎    | 25.9M/48.4M [00:54<00:53, 419kiB/s]

 54%|█████▎    | 26.0M/48.4M [00:54<00:54, 411kiB/s]

 54%|█████▍    | 26.0M/48.4M [00:54<00:56, 399kiB/s]

 54%|█████▍    | 26.1M/48.4M [00:54<00:54, 409kiB/s]

 54%|█████▍    | 26.2M/48.4M [00:54<00:54, 405kiB/s]

 54%|█████▍    | 26.3M/48.4M [00:55<00:52, 426kiB/s]

 54%|█████▍    | 26.3M/48.4M [00:55<00:52, 422kiB/s]

 55%|█████▍    | 26.4M/48.4M [00:55<00:53, 414kiB/s]

 55%|█████▍    | 26.5M/48.4M [00:55<00:54, 404kiB/s]

 55%|█████▍    | 26.5M/48.4M [00:55<00:54, 401kiB/s]

 55%|█████▍    | 26.6M/48.4M [00:55<00:53, 410kiB/s]

 55%|█████▌    | 26.7M/48.4M [00:56<00:55, 394kiB/s]

 55%|█████▌    | 26.8M/48.4M [00:56<00:49, 439kiB/s]

 55%|█████▌    | 26.8M/48.4M [00:56<00:51, 416kiB/s]

 56%|█████▌    | 26.9M/48.4M [00:56<00:52, 411kiB/s]

 56%|█████▌    | 27.0M/48.4M [00:56<00:49, 437kiB/s]

 56%|█████▌    | 27.1M/48.4M [00:56<00:49, 436kiB/s]

 56%|█████▌    | 27.2M/48.4M [00:57<00:52, 408kiB/s]

 56%|█████▌    | 27.2M/48.4M [00:57<00:47, 447kiB/s]

 56%|█████▋    | 27.3M/48.4M [00:57<00:58, 359kiB/s]

 56%|█████▋    | 27.4M/48.4M [00:57<00:51, 408kiB/s]

 57%|█████▋    | 27.4M/48.4M [00:57<00:51, 409kiB/s]

 57%|█████▋    | 27.5M/48.4M [00:58<00:56, 372kiB/s]

 57%|█████▋    | 27.5M/48.4M [00:58<00:54, 380kiB/s]

 57%|█████▋    | 27.6M/48.4M [00:58<00:54, 382kiB/s]

 57%|█████▋    | 27.7M/48.4M [00:58<00:52, 394kiB/s]

 57%|█████▋    | 27.7M/48.4M [00:58<00:52, 392kiB/s]

 57%|█████▋    | 27.8M/48.4M [00:58<00:53, 386kiB/s]

 58%|█████▊    | 27.9M/48.4M [00:59<00:51, 395kiB/s]

 58%|█████▊    | 28.0M/48.4M [00:59<00:47, 430kiB/s]

 58%|█████▊    | 28.0M/48.4M [00:59<00:49, 410kiB/s]

 58%|█████▊    | 28.1M/48.4M [00:59<00:46, 437kiB/s]

 58%|█████▊    | 28.2M/48.4M [00:59<00:47, 423kiB/s]

 58%|█████▊    | 28.3M/48.4M [00:59<00:44, 449kiB/s]

 59%|█████▊    | 28.4M/48.4M [01:00<00:46, 434kiB/s]

 59%|█████▊    | 28.4M/48.4M [01:00<00:44, 448kiB/s]

 59%|█████▉    | 28.5M/48.4M [01:00<00:43, 461kiB/s]

 59%|█████▉    | 28.6M/48.4M [01:00<00:43, 451kiB/s]

 59%|█████▉    | 28.7M/48.4M [01:00<00:42, 464kiB/s]

 59%|█████▉    | 28.8M/48.4M [01:01<00:44, 437kiB/s]

 60%|█████▉    | 28.8M/48.4M [01:01<00:42, 462kiB/s]

 60%|█████▉    | 28.9M/48.4M [01:01<00:41, 472kiB/s]

 60%|█████▉    | 29.0M/48.4M [01:01<00:43, 450kiB/s]

 60%|██████    | 29.1M/48.4M [01:01<00:41, 468kiB/s]

 60%|██████    | 29.2M/48.4M [01:01<00:43, 439kiB/s]

 60%|██████    | 29.2M/48.4M [01:02<00:41, 461kiB/s]

 61%|██████    | 29.3M/48.4M [01:02<00:40, 473kiB/s]

 61%|██████    | 29.4M/48.4M [01:02<00:42, 447kiB/s]

 61%|██████    | 29.5M/48.4M [01:02<00:41, 459kiB/s]

 61%|██████    | 29.6M/48.4M [01:02<00:39, 481kiB/s]

 61%|██████    | 29.6M/48.4M [01:02<00:42, 444kiB/s]

 61%|██████▏   | 29.7M/48.4M [01:03<00:40, 467kiB/s]

 62%|██████▏   | 29.8M/48.4M [01:03<00:38, 480kiB/s]

 62%|██████▏   | 29.9M/48.4M [01:03<00:38, 476kiB/s]

 62%|██████▏   | 30.0M/48.4M [01:03<00:38, 484kiB/s]

 62%|██████▏   | 30.1M/48.4M [01:03<00:37, 486kiB/s]

 62%|██████▏   | 30.2M/48.4M [01:03<00:37, 489kiB/s]

 62%|██████▏   | 30.3M/48.4M [01:04<00:34, 520kiB/s]

 63%|██████▎   | 30.4M/48.4M [01:04<00:35, 512kiB/s]

 63%|██████▎   | 30.5M/48.4M [01:04<00:33, 537kiB/s]

 63%|██████▎   | 30.6M/48.4M [01:04<00:31, 560kiB/s]

 63%|██████▎   | 30.7M/48.4M [01:04<00:31, 569kiB/s]

 64%|██████▎   | 30.8M/48.4M [01:05<00:30, 575kiB/s]

 64%|██████▍   | 30.9M/48.4M [01:05<00:28, 614kiB/s]

 64%|██████▍   | 31.0M/48.4M [01:05<00:27, 636kiB/s]

 64%|██████▍   | 31.1M/48.4M [01:05<00:34, 506kiB/s]

 64%|██████▍   | 31.2M/48.4M [01:05<00:31, 542kiB/s]

 65%|██████▍   | 31.3M/48.4M [01:05<00:27, 614kiB/s]

 65%|██████▍   | 31.4M/48.4M [01:06<00:31, 543kiB/s]

 65%|██████▍   | 31.5M/48.4M [01:06<00:30, 563kiB/s]

 65%|██████▌   | 31.6M/48.4M [01:06<00:29, 581kiB/s]

 65%|██████▌   | 31.7M/48.4M [01:06<00:28, 579kiB/s]

 66%|██████▌   | 31.8M/48.4M [01:06<00:28, 593kiB/s]

 66%|██████▌   | 31.9M/48.4M [01:06<00:34, 483kiB/s]

 66%|██████▌   | 32.0M/48.4M [01:07<00:29, 567kiB/s]

 66%|██████▌   | 32.0M/48.4M [01:07<00:36, 450kiB/s]

 66%|██████▌   | 32.1M/48.4M [01:07<00:35, 460kiB/s]

 66%|██████▋   | 32.2M/48.4M [01:07<00:34, 472kiB/s]

 67%|██████▋   | 32.2M/48.4M [01:07<00:39, 414kiB/s]

 67%|██████▋   | 32.3M/48.4M [01:08<00:39, 413kiB/s]

 67%|██████▋   | 32.4M/48.4M [01:08<00:41, 389kiB/s]

 67%|██████▋   | 32.4M/48.4M [01:08<00:41, 388kiB/s]

 67%|██████▋   | 32.5M/48.4M [01:08<00:41, 381kiB/s]

 67%|██████▋   | 32.6M/48.4M [01:08<00:40, 390kiB/s]

 67%|██████▋   | 32.6M/48.4M [01:08<00:40, 391kiB/s]

 67%|██████▋   | 32.7M/48.4M [01:09<00:40, 392kiB/s]

 68%|██████▊   | 32.8M/48.4M [01:09<00:39, 392kiB/s]

 68%|██████▊   | 32.8M/48.4M [01:09<00:38, 404kiB/s]

 68%|██████▊   | 32.9M/48.4M [01:09<00:39, 398kiB/s]

 68%|██████▊   | 33.0M/48.4M [01:09<00:38, 398kiB/s]

 68%|██████▊   | 33.0M/48.4M [01:09<00:38, 397kiB/s]

 68%|██████▊   | 33.1M/48.4M [01:10<00:39, 391kiB/s]

 68%|██████▊   | 33.2M/48.4M [01:10<00:38, 394kiB/s]

 69%|██████▊   | 33.2M/48.4M [01:10<00:38, 397kiB/s]

 69%|██████▉   | 33.3M/48.4M [01:10<00:37, 404kiB/s]

 69%|██████▉   | 33.4M/48.4M [01:10<00:37, 402kiB/s]

 69%|██████▉   | 33.5M/48.4M [01:10<00:37, 400kiB/s]

 69%|██████▉   | 33.5M/48.4M [01:11<00:37, 396kiB/s]

 69%|██████▉   | 33.6M/48.4M [01:11<00:37, 397kiB/s]

 69%|██████▉   | 33.7M/48.4M [01:11<00:33, 444kiB/s]

 70%|██████▉   | 33.7M/48.4M [01:11<00:34, 433kiB/s]

 70%|██████▉   | 33.8M/48.4M [01:11<00:35, 411kiB/s]

 70%|██████▉   | 33.8M/48.4M [01:11<00:37, 395kiB/s]

 70%|██████▉   | 33.9M/48.4M [01:12<00:35, 407kiB/s]

 70%|███████   | 34.0M/48.4M [01:12<00:31, 456kiB/s]

 70%|███████   | 34.0M/48.4M [01:12<00:32, 448kiB/s]

 70%|███████   | 34.1M/48.4M [01:12<00:35, 408kiB/s]

 70%|███████   | 34.1M/48.4M [01:12<00:31, 450kiB/s]

 71%|███████   | 34.2M/48.4M [01:12<00:31, 451kiB/s]

 71%|███████   | 34.2M/48.4M [01:12<00:33, 422kiB/s]

 71%|███████   | 34.3M/48.4M [01:12<00:31, 447kiB/s]

 71%|███████   | 34.3M/48.4M [01:12<00:31, 445kiB/s]

 71%|███████   | 34.4M/48.4M [01:13<00:32, 434kiB/s]

 71%|███████   | 34.4M/48.4M [01:13<00:27, 509kiB/s]

 71%|███████   | 34.5M/48.4M [01:13<00:28, 495kiB/s]

 71%|███████▏  | 34.6M/48.4M [01:13<00:29, 466kiB/s]

 71%|███████▏  | 34.6M/48.4M [01:13<00:30, 458kiB/s]

 72%|███████▏  | 34.7M/48.4M [01:13<00:27, 495kiB/s]

 72%|███████▏  | 34.7M/48.4M [01:13<00:28, 474kiB/s]

 72%|███████▏  | 34.8M/48.4M [01:13<00:29, 467kiB/s]

 72%|███████▏  | 34.9M/48.4M [01:14<00:25, 529kiB/s]

 72%|███████▏  | 34.9M/48.4M [01:14<00:25, 530kiB/s]

 72%|███████▏  | 35.0M/48.4M [01:14<00:24, 541kiB/s]

 72%|███████▏  | 35.1M/48.4M [01:14<00:22, 586kiB/s]

 73%|███████▎  | 35.2M/48.4M [01:14<00:22, 595kiB/s]

 73%|███████▎  | 35.2M/48.4M [01:14<00:22, 584kiB/s]

 73%|███████▎  | 35.3M/48.4M [01:14<00:29, 443kiB/s]

 73%|███████▎  | 35.5M/48.4M [01:15<00:20, 647kiB/s]

 73%|███████▎  | 35.6M/48.4M [01:15<00:20, 617kiB/s]

 74%|███████▎  | 35.6M/48.4M [01:15<00:22, 581kiB/s]

 74%|███████▎  | 35.7M/48.4M [01:15<00:21, 592kiB/s]

 74%|███████▍  | 35.8M/48.4M [01:15<00:21, 596kiB/s]

 74%|███████▍  | 35.8M/48.4M [01:15<00:22, 564kiB/s]

 74%|███████▍  | 35.9M/48.4M [01:15<00:22, 570kiB/s]

 74%|███████▍  | 36.0M/48.4M [01:15<00:20, 599kiB/s]

 74%|███████▍  | 36.0M/48.4M [01:16<00:22, 547kiB/s]

 75%|███████▍  | 36.1M/48.4M [01:16<00:20, 592kiB/s]

 75%|███████▍  | 36.2M/48.4M [01:16<00:20, 600kiB/s]

 75%|███████▍  | 36.2M/48.4M [01:16<00:20, 602kiB/s]

 75%|███████▍  | 36.3M/48.4M [01:16<00:19, 619kiB/s]

 75%|███████▌  | 36.4M/48.4M [01:16<00:19, 616kiB/s]

 75%|███████▌  | 36.5M/48.4M [01:16<00:19, 615kiB/s]

 75%|███████▌  | 36.6M/48.4M [01:16<00:17, 664kiB/s]

 76%|███████▌  | 36.6M/48.4M [01:17<00:18, 629kiB/s]

 76%|███████▌  | 36.7M/48.4M [01:17<00:16, 707kiB/s]

 76%|███████▌  | 36.8M/48.4M [01:17<00:17, 682kiB/s]

 76%|███████▌  | 36.9M/48.4M [01:17<00:16, 682kiB/s]

 76%|███████▌  | 36.9M/48.4M [01:17<00:17, 652kiB/s]

 76%|███████▋  | 37.0M/48.4M [01:17<00:24, 464kiB/s]

 77%|███████▋  | 37.2M/48.4M [01:17<00:17, 651kiB/s]

 77%|███████▋  | 37.3M/48.4M [01:18<00:18, 612kiB/s]

 77%|███████▋  | 37.3M/48.4M [01:18<00:19, 575kiB/s]

 77%|███████▋  | 37.4M/48.4M [01:18<00:19, 575kiB/s]

 77%|███████▋  | 37.5M/48.4M [01:18<00:19, 570kiB/s]

 77%|███████▋  | 37.5M/48.4M [01:18<00:20, 539kiB/s]

 78%|███████▊  | 37.6M/48.4M [01:18<00:17, 615kiB/s]

 78%|███████▊  | 37.7M/48.4M [01:18<00:18, 581kiB/s]

 78%|███████▊  | 37.7M/48.4M [01:18<00:24, 444kiB/s]

 78%|███████▊  | 37.8M/48.4M [01:19<00:19, 536kiB/s]

 78%|███████▊  | 37.9M/48.4M [01:19<00:19, 533kiB/s]

 78%|███████▊  | 37.9M/48.4M [01:19<00:27, 382kiB/s]

 79%|███████▊  | 38.0M/48.4M [01:19<00:22, 460kiB/s]

 79%|███████▊  | 38.1M/48.4M [01:19<00:22, 463kiB/s]

 79%|███████▊  | 38.1M/48.4M [01:19<00:24, 413kiB/s]

 79%|███████▉  | 38.2M/48.4M [01:20<00:25, 403kiB/s]

 79%|███████▉  | 38.2M/48.4M [01:20<00:25, 401kiB/s]

 79%|███████▉  | 38.3M/48.4M [01:20<00:29, 342kiB/s]

 79%|███████▉  | 38.3M/48.4M [01:20<00:27, 370kiB/s]

 79%|███████▉  | 38.4M/48.4M [01:20<00:36, 278kiB/s]

 79%|███████▉  | 38.5M/48.4M [01:20<00:29, 343kiB/s]

 79%|███████▉  | 38.5M/48.4M [01:20<00:28, 348kiB/s]

 80%|███████▉  | 38.5M/48.4M [01:21<00:28, 348kiB/s]

 80%|███████▉  | 38.6M/48.4M [01:21<00:29, 337kiB/s]

 80%|███████▉  | 38.6M/48.4M [01:21<00:34, 289kiB/s]

 80%|███████▉  | 38.6M/48.4M [01:21<00:37, 261kiB/s]

 80%|███████▉  | 38.7M/48.4M [01:21<00:35, 274kiB/s]

 80%|███████▉  | 38.8M/48.4M [01:21<00:34, 284kiB/s]

 80%|████████  | 38.8M/48.4M [01:22<00:29, 325kiB/s]

 80%|████████  | 38.8M/48.4M [01:22<00:30, 315kiB/s]

 80%|████████  | 38.9M/48.4M [01:22<00:31, 306kiB/s]

 80%|████████  | 38.9M/48.4M [01:22<00:31, 303kiB/s]

 80%|████████  | 39.0M/48.4M [01:22<00:31, 301kiB/s]

 81%|████████  | 39.0M/48.4M [01:22<00:31, 301kiB/s]

 81%|████████  | 39.1M/48.4M [01:22<00:27, 338kiB/s]

 81%|████████  | 39.1M/48.4M [01:23<00:28, 332kiB/s]

 81%|████████  | 39.2M/48.4M [01:23<00:29, 319kiB/s]

 81%|████████  | 39.2M/48.4M [01:23<00:29, 309kiB/s]

 81%|████████  | 39.3M/48.4M [01:23<00:30, 306kiB/s]

 81%|████████  | 39.3M/48.4M [01:23<00:29, 308kiB/s]

 81%|████████  | 39.4M/48.4M [01:23<00:26, 338kiB/s]

 81%|████████▏ | 39.4M/48.4M [01:23<00:26, 340kiB/s]

 81%|████████▏ | 39.4M/48.4M [01:24<00:28, 319kiB/s]

 81%|████████▏ | 39.5M/48.4M [01:24<00:25, 356kiB/s]

 82%|████████▏ | 39.5M/48.4M [01:24<00:25, 350kiB/s]

 82%|████████▏ | 39.6M/48.4M [01:24<00:27, 329kiB/s]

 82%|████████▏ | 39.6M/48.4M [01:24<00:28, 310kiB/s]

 82%|████████▏ | 39.7M/48.4M [01:24<00:25, 341kiB/s]

 82%|████████▏ | 39.7M/48.4M [01:24<00:25, 339kiB/s]

 82%|████████▏ | 39.7M/48.4M [01:24<00:27, 319kiB/s]

 82%|████████▏ | 39.8M/48.4M [01:25<00:25, 344kiB/s]

 82%|████████▏ | 39.8M/48.4M [01:25<00:22, 375kiB/s]

 82%|████████▏ | 39.9M/48.4M [01:25<00:23, 368kiB/s]

 82%|████████▏ | 39.9M/48.4M [01:25<00:24, 346kiB/s]

 83%|████████▎ | 40.0M/48.4M [01:25<00:24, 350kiB/s]

 83%|████████▎ | 40.0M/48.4M [01:25<00:22, 378kiB/s]

 83%|████████▎ | 40.1M/48.4M [01:25<00:22, 379kiB/s]

 83%|████████▎ | 40.1M/48.4M [01:25<00:22, 374kiB/s]

 83%|████████▎ | 40.2M/48.4M [01:26<00:23, 347kiB/s]

 83%|████████▎ | 40.2M/48.4M [01:26<00:22, 362kiB/s]

 83%|████████▎ | 40.3M/48.4M [01:26<00:21, 376kiB/s]

 83%|████████▎ | 40.4M/48.4M [01:26<00:18, 431kiB/s]

 83%|████████▎ | 40.4M/48.4M [01:26<00:19, 420kiB/s]

 84%|████████▎ | 40.5M/48.4M [01:26<00:19, 407kiB/s]

 84%|████████▎ | 40.5M/48.4M [01:26<00:19, 404kiB/s]

 84%|████████▍ | 40.6M/48.4M [01:27<00:17, 443kiB/s]

 84%|████████▍ | 40.7M/48.4M [01:27<00:16, 462kiB/s]

 84%|████████▍ | 40.7M/48.4M [01:27<00:17, 445kiB/s]

 84%|████████▍ | 40.8M/48.4M [01:27<00:16, 461kiB/s]

 84%|████████▍ | 40.9M/48.4M [01:27<00:14, 537kiB/s]

 85%|████████▍ | 40.9M/48.4M [01:27<00:14, 526kiB/s]

 85%|████████▍ | 41.0M/48.4M [01:27<00:14, 524kiB/s]

 85%|████████▍ | 41.1M/48.4M [01:27<00:12, 593kiB/s]

 85%|████████▍ | 41.2M/48.4M [01:28<00:12, 602kiB/s]

 85%|████████▌ | 41.2M/48.4M [01:28<00:12, 581kiB/s]

 85%|████████▌ | 41.3M/48.4M [01:28<00:11, 631kiB/s]

 86%|████████▌ | 41.4M/48.4M [01:28<00:09, 719kiB/s]

 86%|████████▌ | 41.5M/48.4M [01:28<00:10, 673kiB/s]

 86%|████████▌ | 41.6M/48.4M [01:28<00:13, 514kiB/s]

 86%|████████▌ | 41.7M/48.4M [01:28<00:13, 507kiB/s]

 86%|████████▌ | 41.8M/48.4M [01:29<00:11, 589kiB/s]

 86%|████████▋ | 41.8M/48.4M [01:29<00:10, 615kiB/s]

 87%|████████▋ | 41.9M/48.4M [01:29<00:09, 655kiB/s]

 87%|████████▋ | 42.0M/48.4M [01:29<00:10, 643kiB/s]

 87%|████████▋ | 42.1M/48.4M [01:29<00:10, 630kiB/s]

 87%|████████▋ | 42.1M/48.4M [01:29<00:09, 636kiB/s]

 87%|████████▋ | 42.2M/48.4M [01:29<00:10, 612kiB/s]

 87%|████████▋ | 42.3M/48.4M [01:29<00:10, 576kiB/s]

 88%|████████▊ | 42.4M/48.4M [01:30<00:08, 683kiB/s]

 88%|████████▊ | 42.5M/48.4M [01:30<00:08, 724kiB/s]

 88%|████████▊ | 42.6M/48.4M [01:30<00:08, 724kiB/s]

 88%|████████▊ | 42.7M/48.4M [01:30<00:08, 682kiB/s]

 88%|████████▊ | 42.8M/48.4M [01:30<00:07, 710kiB/s]

 89%|████████▊ | 42.9M/48.4M [01:30<00:07, 742kiB/s]

 89%|████████▊ | 43.0M/48.4M [01:30<00:07, 695kiB/s]

 89%|████████▉ | 43.1M/48.4M [01:30<00:07, 746kiB/s]

 89%|████████▉ | 43.2M/48.4M [01:31<00:06, 802kiB/s]

 89%|████████▉ | 43.3M/48.4M [01:31<00:06, 788kiB/s]

 89%|████████▉ | 43.4M/48.4M [01:31<00:07, 681kiB/s]

 90%|████████▉ | 43.5M/48.4M [01:31<00:06, 788kiB/s]

 90%|█████████ | 43.6M/48.4M [01:31<00:05, 840kiB/s]

 90%|█████████ | 43.7M/48.4M [01:31<00:08, 585kiB/s]

 90%|█████████ | 43.8M/48.4M [01:32<00:06, 674kiB/s]

 91%|█████████ | 43.9M/48.4M [01:32<00:06, 696kiB/s]

 91%|█████████ | 44.0M/48.4M [01:32<00:06, 696kiB/s]

 91%|█████████ | 44.1M/48.4M [01:32<00:07, 615kiB/s]

 91%|█████████ | 44.1M/48.4M [01:32<00:07, 585kiB/s]

 91%|█████████▏| 44.3M/48.4M [01:32<00:06, 631kiB/s]

 92%|█████████▏| 44.4M/48.4M [01:32<00:05, 690kiB/s]

 92%|█████████▏| 44.4M/48.4M [01:33<00:06, 660kiB/s]

 92%|█████████▏| 44.5M/48.4M [01:33<00:06, 634kiB/s]

 92%|█████████▏| 44.6M/48.4M [01:33<00:05, 686kiB/s]

 92%|█████████▏| 44.7M/48.4M [01:33<00:04, 770kiB/s]

 92%|█████████▏| 44.8M/48.4M [01:33<00:04, 735kiB/s]

 93%|█████████▎| 44.9M/48.4M [01:33<00:05, 700kiB/s]

 93%|█████████▎| 45.0M/48.4M [01:33<00:04, 693kiB/s]

 93%|█████████▎| 45.1M/48.4M [01:33<00:04, 772kiB/s]

 93%|█████████▎| 45.2M/48.4M [01:34<00:04, 759kiB/s]

 94%|█████████▎| 45.3M/48.4M [01:34<00:04, 718kiB/s]

 94%|█████████▎| 45.4M/48.4M [01:34<00:03, 763kiB/s]

 94%|█████████▍| 45.5M/48.4M [01:34<00:03, 825kiB/s]

 94%|█████████▍| 45.6M/48.4M [01:34<00:03, 749kiB/s]

 94%|█████████▍| 45.7M/48.4M [01:34<00:03, 739kiB/s]

 95%|█████████▍| 45.8M/48.4M [01:34<00:03, 804kiB/s]

 95%|█████████▍| 46.0M/48.4M [01:34<00:02, 849kiB/s]

 95%|█████████▌| 46.1M/48.4M [01:35<00:02, 811kiB/s]

 95%|█████████▌| 46.1M/48.4M [01:35<00:03, 762kiB/s]

 95%|█████████▌| 46.3M/48.4M [01:35<00:02, 810kiB/s]

 96%|█████████▌| 46.3M/48.4M [01:35<00:02, 800kiB/s]

 96%|█████████▌| 46.4M/48.4M [01:35<00:02, 774kiB/s]

 96%|█████████▌| 46.5M/48.4M [01:35<00:02, 824kiB/s]

 96%|█████████▋| 46.7M/48.4M [01:35<00:02, 874kiB/s]

 97%|█████████▋| 46.8M/48.4M [01:35<00:02, 780kiB/s]

 97%|█████████▋| 46.8M/48.4M [01:36<00:02, 749kiB/s]

 97%|█████████▋| 46.9M/48.4M [01:36<00:02, 560kiB/s]

 97%|█████████▋| 47.0M/48.4M [01:36<00:02, 571kiB/s]

 97%|█████████▋| 47.2M/48.4M [01:36<00:01, 744kiB/s]

 98%|█████████▊| 47.3M/48.4M [01:36<00:01, 726kiB/s]

 98%|█████████▊| 47.3M/48.4M [01:36<00:01, 687kiB/s]

 98%|█████████▊| 47.4M/48.4M [01:37<00:01, 605kiB/s]

 98%|█████████▊| 47.5M/48.4M [01:37<00:01, 602kiB/s]

 98%|█████████▊| 47.6M/48.4M [01:37<00:01, 681kiB/s]

 98%|█████████▊| 47.7M/48.4M [01:37<00:01, 502kiB/s]

 99%|█████████▊| 47.8M/48.4M [01:37<00:01, 583kiB/s]

 99%|█████████▉| 47.9M/48.4M [01:37<00:01, 566kiB/s]

 99%|█████████▉| 47.9M/48.4M [01:38<00:00, 518kiB/s]

 99%|█████████▉| 48.0M/48.4M [01:38<00:00, 559kiB/s]

 99%|█████████▉| 48.1M/48.4M [01:38<00:00, 529kiB/s]

 99%|█████████▉| 48.2M/48.4M [01:38<00:00, 505kiB/s]

 99%|█████████▉| 48.2M/48.4M [01:38<00:00, 375kiB/s]

100%|█████████▉| 48.3M/48.4M [01:38<00:00, 517kiB/s]

100%|█████████▉| 48.4M/48.4M [01:39<00:00, 477kiB/s]

100%|██████████| 48.4M/48.4M [01:39<00:00, 489kiB/s]

Loading the zipfile...

Loading completed.
Total JARVIS-DFT 3D entries: 93902
Example keys: ['Tc_supercon', 'atoms', 'avg_elec_mass', 'avg_hole_mass', 'bulk_modulus_kv', 'crys', 'density', 'dfpt_piezo_max_dielectric', 'dfpt_piezo_max_dielectric_electronic', 'dfpt_piezo_max_dielectric_ionic', 'dfpt_piezo_max_dij', 'dfpt_piezo_max_eij', 'dimensionality', 'effective_masses_300K', 'efg', 'ehull', 'elastic_tensor', 'encut', 'epsx', 'epsy'] ...

In [6]:
def jarvis_to_numeric(x):
    """JARVIS encodes missing values as the string 'na'."""
    try:
        if x is None:
            return np.nan
        if isinstance(x, str) and x.strip().lower() == "na":
            return np.nan
        return float(x)
    except Exception:
        return np.nan


# Pre-filter to entries that actually have a Seebeck value, to avoid building
# ~76,000 pymatgen structures (slow). This keeps only the ~22k relevant rows.
seebeck_entries = [
    e for e in dft_3d
    if not (pd.isna(jarvis_to_numeric(e.get("n-Seebeck"))) and pd.isna(jarvis_to_numeric(e.get("p-Seebeck"))))
]
print("Entries with at least one non-null Seebeck value:", len(seebeck_entries))

rows = []
for e in tqdm(seebeck_entries, desc="classifying JARVIS-DFT Seebeck entries"):
    try:
        jatoms = JarvisAtoms.from_dict(e["atoms"])
        structure = jatoms.pymatgen_converter()
    except Exception:
        continue
    fam = classify_family(structure)
    try:
        sgnum = SpacegroupAnalyzer(structure, symprec=0.1).get_space_group_number()
    except Exception:
        sgnum = None
    rows.append({
        "jid": e.get("jid"),
        "formula": e.get("formula"),
        "space_group_number": sgnum,
        "family": fam,
        "n_seebeck": jarvis_to_numeric(e.get("n-Seebeck")),
        "p_seebeck": jarvis_to_numeric(e.get("p-Seebeck")),
        "n_powerfact": jarvis_to_numeric(e.get("n-powerfact")),
        "p_powerfact": jarvis_to_numeric(e.get("p-powerfact")),
    })

df_jarvis = pd.DataFrame(rows)
print("\nFamily counts (JARVIS-DFT, Seebeck subset):")
print(df_jarvis["family"].value_counts(dropna=True))

for fam in FAMILIES:
    sub = df_jarvis[df_jarvis["family"] == fam]
    save_family_csv(sub, "jarvis_dft", fam)

Entries with at least one non-null Seebeck value: 23218

classifying JARVIS-DFT Seebeck entries:   0%|          | 0/23218 [00:00<?, ?it/s]

C:\Users\Ekta Jain\AppData\Local\Programs\Python\Python311\Lib\functools.py:1001: UserWarning: No Pauling electronegativity for He. Setting to NaN. This has no physical meaning, and is mainly done to avoid errors caused by the code expecting a float.
  val = self.func(instance)

C:\Users\Ekta Jain\AppData\Local\Programs\Python\Python311\Lib\functools.py:1001: UserWarning: No Pauling electronegativity for Ne. Setting to NaN. This has no physical meaning, and is mainly done to avoid errors caused by the code expecting a float.
  val = self.func(instance)

Family counts (JARVIS-DFT, Seebeck subset):
family
half_heusler     439
skutterudite      37
bi2te3_family      4
Name: count, dtype: int64
  jarvis_dft             | half_heusler    |    439 rows -> /content/te_family_csvs\jarvis_dft__half_heusler.csv
  jarvis_dft             | skutterudite    |     37 rows -> /content/te_family_csvs\jarvis_dft__skutterudite.csv
  jarvis_dft             | bi2te3_family   |      4 rows -> /content/te_family_csvs\jarvis_dft__bi2te3_family.csv

## Section C (optional) — Full Ricci tabular (47,737 entries) via live Materials Project lookup

This is the *complete* Ricci et al. dataset (bigger than `boltztrap_mp` in Section A, but it doesn't ship with structures — only `mpid`s). To classify by family we need each structure's space group, which we fetch live from the Materials Project API in batches.

**Requires a free API key:** create one at https://materialsproject.org/api and paste it below. Skip this section if you don't want to sign up — Sections A and B already give you real counts.

In [7]:
MP_API_KEY = ""  # <-- paste your Materials Project API key here, or leave blank to skip this section

if MP_API_KEY:
    from matminer.datasets import load_dataset
    from mp_api.client import MPRester

    df_ricci_full = load_dataset("ricci_boltztrap_mp_tabular")
    print(df_ricci_full.shape)
    print(df_ricci_full.columns.tolist())

    # mpid column name may be 'mpid' or 'task' depending on matminer version -- check both
    id_col = "mpid" if "mpid" in df_ricci_full.columns else "task"
    all_ids = df_ricci_full[id_col].dropna().unique().tolist()
    print(f"Unique material IDs to look up: {len(all_ids)}")

    symmetry_records = []
    batch_size = 1000
    with MPRester(MP_API_KEY) as mpr:
        for i in tqdm(range(0, len(all_ids), batch_size), desc="querying MP summary"):
            batch = all_ids[i : i + batch_size]
            docs = mpr.materials.summary.search(
                material_ids=batch,
                fields=["material_id", "formula_pretty", "symmetry", "structure"],
            )
            for d in docs:
                symmetry_records.append({
                    "mpid": str(d.material_id),
                    "formula_pretty": d.formula_pretty,
                    "space_group_number": d.symmetry.number if d.symmetry else None,
                    "structure": d.structure,
                })

    df_sym = pd.DataFrame(symmetry_records)
    print("Fetched symmetry/structure for", len(df_sym), "materials")

    df_sym["family"] = df_sym["structure"].progress_apply(classify_family) if hasattr(df_sym["structure"], "progress_apply") else df_sym["structure"].apply(classify_family)

    merged = df_ricci_full.merge(df_sym[["mpid", "space_group_number", "family"]], left_on=id_col, right_on="mpid", how="left")

    seebeck_cols = [c for c in merged.columns if "S." in c or "seebeck" in c.lower()]
    print("Detected Seebeck-related columns:", seebeck_cols)

    for fam in FAMILIES:
        sub = merged[
            (merged["family"] == fam) & (merged[seebeck_cols].notna().any(axis=1))
        ]
        save_family_csv(sub, "ricci_full_mp_api", fam)
else:
    print("MP_API_KEY not set -- skipping Section C. Get a free key at https://materialsproject.org/api")

MP_API_KEY not set -- skipping Section C. Get a free key at https://materialsproject.org/api

## Summary table (dataset × family → number of Seebeck data points)

In [8]:
summary_df = pd.DataFrame(summary_rows, columns=["dataset", "family", "n_seebeck_datapoints"])
pivot = summary_df.pivot_table(index="family", columns="dataset", values="n_seebeck_datapoints", fill_value=0, aggfunc="sum")
pivot = pivot.reindex(FAMILIES)

summary_path = os.path.join(OUT_DIR, "summary_table.csv")
pivot.to_csv(summary_path)

print("Saved summary table to:", summary_path)
pivot

Saved summary table to: /content/te_family_csvs\summary_table.csv

dataset        jarvis_dft  ricci_boltztrap_mp
family
half_heusler          439                   9
skutterudite           37                   1
bi2te3_family           4                   0

In [9]:
# Zip everything up for easy download from Colab
import shutil

zip_path = shutil.make_archive("/content/te_family_csvs", "zip", OUT_DIR)
print("Zipped output ready at:", zip_path)

try:
    from google.colab import files
    files.download(zip_path)
except Exception as e:
    print("Not running in Colab (or download blocked) -- files are at:", OUT_DIR, "and", zip_path)

Zipped output ready at: C:\content\te_family_csvs.zip
Not running in Colab (or download blocked) -- files are at: /content/te_family_csvs and C:\content\te_family_csvs.zip